version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./bot.log:/app/bot.log
      - ./config.py:/app/config.py
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
